server:
  port: 8080

spring:
  application:
    name: chat
  datasource:
    url: jdbc:postgresql://192.168.100.131:5432/chat
    username: postgres
    password: 512218
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # 返回 JSON 时忽略非空字段

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dely.chat.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # 对应数据库的序列自增

logging:
  level:
    com.dely.chat:
      mapper: debug
      service: info
      controller: info